---
- hosts: "{{ specified_hosts }}"
  vars_files:
    - v1
    - v2
  tasks:
    - name: Check users
      shell: id
      register: res
      
    - name: Show
      debug:
        msg: "{{ res }}"

    - name: show host var
      shell: echo {{kupa}}
      register: kres

    - name: Show kres
      debug:
        msg: "{{ kres }}"

    - name: show dupa
      debug:
        msg: "{{ msg1 }}"

    - name: show dupa2
      debug:
        msg: "{{ msg2 }}"
...
