---
- hosts: "{{ specified_hosts }}"
  tasks:
    - name: Check users
      shell: id
      register: res
      
    - name: Show
      debug:
        msg: "{{ res }}"

    - name: show host var
      shell: echo $kupa
      register: kres

    - name: Show kres
      debug:
        msg: "{{ kres }}"
...
