---
- hosts: server30.example.com
  tasks:
    - name: Check users
      shell: id > /tmp/wynik
      delegate_to: amaster1.example.com

   - name: cat on server30
     shell: cat /tmp/wynik
     ignore_errors: yes

- hosts: amaster1.example.com
  tasks:
   - name: cat on amaster1
     shell: cat /tmp/wynik
     ignore_errors: yes
...
